Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,12 +37,23 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y jq unzip
+
+      - name: Debug AWS Region secret
+        run: |
+          if [ -z "${{ secrets.AWS_DEFAULT_REGION }}" ]; then
+            echo "❌ AWS_DEFAULT_REGION is empty or missing"
+            exit 1
+          else
+            echo "✅ AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}"
+          fi
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+
 
       - name: Login to Amazon ECR
         id: login-ecr
